name: build-cpp

on:
    push:
      branches: [compile]
    pull_request:
      branches: [compile]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

    #  - name: Install compiler (Linux)
     #   if: matrix.os == 'ubuntu-latest'
        #run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile
        run: |
         if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          g++ cppsp_compiler.cpp -Os -s -std=c++17 -o cppsp_compiler_linux -static
          else
           clang++ cppsp_compiler.cpp -Os -std=c++17 -o cppsp_compiler_mac
            fi

      - name: Upload artifact
        if: matrix.os == 'ubuntu-latest'
        run: |
           zip binaries.zip cppsp_compiler_linux cppsp_compiler_mac
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name:  binary
          path: binaries.zip
